version: '3.8'

services:
  bib-extractor:
    build: .
    container_name: bib-extractor
    platform: linux/amd64
    ports:
      - "9000:8080"
    environment:
      DATABASE_HOST: fitistan-staging.c3i82myqanzr.ap-south-1.rds.amazonaws.com
      DATABASE_PORT: 5432
      DATABASE_NAME: faceprocessing
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Postgress*Fitistan*0105
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ap-south-1
